name: Test

on:
  push:
  pull_request:

jobs:
  node:
    name: API Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        working-directory: api
      # - run: npm test
      - run: npm run build
        working-directory: api
        env:
          CI: true
