name: Lint

on:
  push:
  pull_request:

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: |
          npm run prettier:check
